# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello": "00_core.ipynb",
         "mult": "01.ipynb",
         "add": "01.ipynb",
         "subtract": "01.ipynb"}

modules = ["core.py",
           "sec.py"]

doc_url = "https://d-genk.github.io/n2s/"

git_url = "https://github.com/d-genk/n2s/tree/master/"

def custom_doc_links(name): return None
