# AUTOGENERATED! DO NOT EDIT! File to edit: 01.ipynb (unless otherwise specified).

__all__ = ['mult', 'add', 'subtract']

# Cell
def mult(one, two):
    return one*two

# Cell

def add(one, two):
    return one+two

# Cell
def subtract(one, two):
    return two - one